from . import figures
from .schema import schema

try:
    # NOTE: the `version.py` file must not be present in the git repository
    #   as it is generated by setuptools at install time
    from .version import __version__
except ImportError:  # pragma: no cover
    # Local copy or not installed with setuptools
    __version__ = "999"


@figures.Figure.new_if_none()
def line(*args, fig=None, **kwargs):
    return fig.add_line(*args, **kwargs)


@figures.Figure.new_if_none()
def scatter(*args, fig=None, **kwargs):
    return fig.add_scatter(*args, **kwargs)


@figures.Figure.new_if_none()
def bar(*args, fig=None, **kwargs):
    return fig.add_bar(*args, **kwargs)


@figures.Figure.new_if_none()
def envelope(*args, fig=None, **kwargs):
    return fig.add_envelope(*args, **kwargs)


@figures.Figure.new_if_none(schema=schema.figures.stripes)
def stripes(*args, fig=None, **kwargs):
    return fig.add_stripes(*args, **kwargs)
